name: build 
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clone the repository and checkout into the relevant branch
      - uses: actions/checkout@v4

      # Install Ruby
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4 # Check https://pages.github.com/versions/ for the current Ruby version used by gh pages.

      # Install dependencies required to run jekyll build
      - name: Install gh-pages rubygem via bundler
        run: |
          # Update gem and bundler
          gem update --system --no-document
          gem update bundler --no-document
          # Set the bundle directory
          bundle config set path vendor/bundle
          # Install Gemfile contents via bundler
          bundle install

      # Build the website via jekyll
      - name: Build jekyll website with drafts
        run: bundle exec jekyll build --drafts
    